defaultContentLanguage: "zh-CN"
baseurl: 'https://threetalks.com'
languageCode: "zh-CN"
theme: hello-friend
enableemoji: true
enablegitinfo: true
paginate: 5
publishDir: docs
params:
  contentTypeName: posts
  defaultTheme: light
  showMenuItems: 4
  showReadingTime: True
  toc: true
  rssFullText: true
languages:
  zh-CN:
    title: Three Talks
    copyright: '&copy; 2021 - 2022  Three Talks. All rights reserved.'
    subtitle: 'Talk code, money, life'
    keywords: [ 'code','money','life',"代码","搞钱","生活" ]
    menuMore: 展示更多
    writtenBy: Written by
    readMore: 阅读更多
    readOtherPosts: 阅读其他文章
    newerPosts: 最新文章
    olderPosts: 历史文章
    minuteReadingTime: 最短阅读时长
    dateFormatSingle: '2006-01-02'
    dateFormatList: '2006-01-02'
    params:
      logo:
        logoText: Three Talks
        logoHomeLink: /

